// <auto-generated />
using DemoEFCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoEFCodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260116092813_AddConfigurations")]
    partial class AddConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoEFCodeFirst.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Sam",
                            Lastname = "Worthington"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Zoe",
                            Lastname = "Saldaña"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Sigourney",
                            Lastname = "Weaver"
                        });
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Creator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Creators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "James",
                            Lastname = "Cameron"
                        });
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("int")
                        .HasComment("L'année de sortie du film");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Films", null, t =>
                        {
                            t.HasCheckConstraint("CK_Film_ReleasedYear_Before1950", "ReleasedYear >= 1950");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            ReleasedYear = 2009,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            ReleasedYear = 2022,
                            Title = "Avatar 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            ReleasedYear = 2025,
                            Title = "Avatar 3"
                        });
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.FilmActor", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmActors");
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Film", b =>
                {
                    b.HasOne("DemoEFCodeFirst.Models.Creator", "Creator")
                        .WithMany("Films")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.FilmActor", b =>
                {
                    b.HasOne("DemoEFCodeFirst.Models.Actor", "Actor")
                        .WithMany("Films")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoEFCodeFirst.Models.Film", "Film")
                        .WithMany("Actors")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Actor", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Creator", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("DemoEFCodeFirst.Models.Film", b =>
                {
                    b.Navigation("Actors");
                });
#pragma warning restore 612, 618
        }
    }
}
